source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WTAlert_Example' do
  pod 'WTAlert', :path => '../'
end

target 'WTAlert_Tests' do
  inherit! :search_paths
  pod 'WTAlert', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
